### ISSUE TITLE
Bounding box coordinates not comming properly

### ISSUE THREAD

**Issue by mr-mainak** [marcoslucianops/DeepStream-Yolo#626]
Hi @marcoslucianops 
here is the screenshot of my output:
```
start
uid: 1
left: 0 top: 0 right: 2 bottom: 3
auto
Running Area Speed
**********
start
uid: 1
left: 0 top: 0 right: 11 bottom: 11
auto
Running Area Speed
**********
start
uid: 1
left: 1 top: 0 right: 9 bottom: 5
car
Running Area Speed
```
As you can see left, top, right, bottom values are not coming properly. Parsing is not happening as a result I cannot see the detection. I'm using ```c11c3e4a7836aac501ab38cfe85985f557bf5037``` commit. Any help is highly appreciated

Here is the pgie config that I'm using:
```
property:
  gpu-id: 0
  net-scale-factor: 0.0039215697906911373
  model-color-format: 0
  # onnx-file: ./best_v3.0.onnx
  # model-file: ./class_19.weights
  # custom-network-config: ./models/class_19.cfg
  model-engine-file: ./vehicle_detection_v3.0.engine
  #int8-calib-file=calib.table
  labelfile-path: ./labels_pgie_v5.txt
  batch-size: 1
  network-mode: 2
  num-detected-classes: 5
  interval: 0
  gie-unique-id: 1
  process-mode: 1
  network-type: 0
  cluster-mode: 2
  maintain-aspect-ratio: 1
  symmetric-padding: 1
  #workspace-size=2000
  parse-bbox-func-name: NvDsInferParseYolo
  #parse-bbox-func-name=NvDsInferParseYoloCuda
  custom-lib-path: vehicle_detection_1.so
  engine-create-func-name: NvDsInferYoloCudaEngineGet
class-attrs-all:
  pre-cluster-threshold: 0.2
  topk: 20
  nms-iou-threshold: 0.5
```
