### ISSUE TITLE
No detection on my Jetson Orin Nano

### ISSUE THREAD

**Issue by javijurado** [marcoslucianops/DeepStream-Yolo#646]
I have my own deepstream pipeline to detect vehicles. Before I was using Yolo v4 but then I decided to migrate to YoloX. After training, exporting and loading my onnx file into the system no detection at all. The pipeline whole pipeline was working because I was able to see the video streaming.
I tested on a Jetson Orin AGX and detection is working with the new network.

Jetson Orin Nano is using Jetpack 6.1 with Deepstream 7.1
Jeston Orin AGX is using Jetpack 6.0 with Deepstream 7.0

My config file is the following one (same for both system):
```
[property]
gpu-id=0
net-scale-factor=1.0
model-color-format=0
model-engine-file=../models/model_b1_gpu0_fp32.engine
onnx-file=../models/yolo-x/best_ckpt.onnx
labelfile-path=../models/yolo-x/labels.txt
batch-size=1
network-mode=0
num-detected-classes=1
interval=0
gie-unique-id=1
process-mode=1
network-type=0
cluster-mode=2
maintain-aspect-ratio=1
symmetric-padding=0
parse-bbox-func-name=NvDsInferParseYolo
custom-lib-path=../DeepStream-Yolo/nvdsinfer_custom_impl_Yolo/libnvdsinfer_custom_impl_Yolo.so
engine-create-func-name=NvDsInferYoloCudaEngineGet

[class-attrs-all]
nms-iou-threshold=0.45
pre-cluster-threshold=0.25
topk=300

```

Also FYI: I'm using Yolox Large model

I used this script to port my model
https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/utils/export_yolox.py

using the following comand
python3 export_yolox.py -w best_ckpt.pth -c exps/default/ft_yolox_l.py --dynamic

Any advise on this?

Device info:
```
Software part of jetson-stats 4.3.2 - (c) 2024, Raffaello Bonghi
Model: NVIDIA Jetson Orin NX Engineering Reference Developer Kit - Jetpack 6.1 [L4T 36.4.0]
NV Power Mode[0]: 15W
Serial Number: [XXX Show with: jetson_release -s XXX]
Hardware:
 - P-Number: p3767-0003
 - Module: NVIDIA Jetson Orin Nano (8GB ram)
Platform:
 - Distribution: Ubuntu 22.04 Jammy Jellyfish
 - Release: 5.15.148-tegra
jtop:
 - Version: 4.3.2
 - Service: Active
Libraries:
 - CUDA: 12.6.68
 - cuDNN: 9.3.0.75
 - TensorRT: 10.3.0.30
 - VPI: 3.2.4
 - OpenCV: 4.8.0 - with CUDA: NO
```
